server:
  port: 8888

management:
  security:
    enabled: false

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///c/Users/emallmann/Documents/Treinamento/Microservices/Labs/spring-cloud/lab1