server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
#          uri: file:///c/Users/emallmann/Documents/Treinamento/Microservices/Labs/spring-cloud/lab1
          uri: file://home/eduardo/Documents/Treinamento/spring-cloud/spring-cloud-lab1/spring-cloud-config-repo